version: '3'

services:
  udonite-server:
    build:
      context: ./udonite-server
      dockerfile: Dockerfile
      args:
        - USERNAME=${USERNAME}
        - GROUPNAME=${GROUPNAME}
        - USERID=${USERID}
        - GROUPID=${GROUPID}
    image: udonite/udonite-server
    container_name: udonite-server
    volumes:
      - type: bind
        source: ./public_html
        target: /var/www/public_html
  nginx-prod:
    build:
      context: ./nginx-prod
      dockerfile: Dockerfile
    image: udonite/nginx-prod
    container_name: udonite-nginx
    depends_on:
      - udonite-server
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - host.env
    volumes:
      - type: bind
        source: ./public_html
        target: /var/www/public_html
        read_only: true
      - type: bind
        source: ./letsencrypt/etc_letsencrypt
        target: /etc/letsencrypt
        read_only: true
