# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.0.2
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: udonite
  name: udonite
spec:
  containers:
  - args:
    - ./run.sh
    envFrom:
    - configMapRef:
        name: envmap
        optional: false
    image: localhost/udonite/udonite-server:latest
    name: server
    ports:
    - containerPort: 80
      hostPort: 80
    - containerPort: 443
      hostPort: 443
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/www/public_html:Z
      name: udonite-container-public_html-host-0
  - args:
    - nginx
    - -g
    - daemon off;
    envFrom:
    - configMapRef:
        name: envmap
        optional: false
    image: localhost/udonite/nginx-prod:latest
    name: nginx
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/www/public_html:Z
      name: udonite-container-public_html-host-0
      readOnly: true
    - mountPath: /etc/letsencrypt:Z
      name: udonite-container-letsencrypt-etc_letsencrypt-host-1
      readOnly: true
  hostAliases:
  - hostnames:
    - udonite-server
    ip: 127.0.0.1
  restartPolicy: Never
  volumes:
  - hostPath:
      path: ./public_html
      type: Directory
    name: udonite-container-public_html-host-0
  - hostPath:
      path: ./letsencrypt/etc_letsencrypt
      type: Directory
    name: udonite-container-letsencrypt-etc_letsencrypt-host-1
status: {}
